### ISSUE TITLE
SQL Injection Vulnerability

### ISSUE THREAD

**Issue by adamweingram** [Apro123/Express-sqlite3-setup#1]
Just wanted to let you know that using javascript templates with SQL means injection attacks are trivial. (see [here](https://github.com/Apro123/Express-sqlite3-setup/blob/76072aa46292efad82412089ccb5fdbbbd099614/index.js#L20)). It's better to use `?` with API functions that aren't vulnerable.

**Comment by Apro123** [comment]
Oh yes. Thank you for that. I plan to fix that soon

**Comment by Apro123** [comment]
See PR
